### ISSUE TITLE
Replace availablePoints with availableMoves

### ISSUE THREAD

**Issue by pardahlman** [Korla/hexgame#3]
The main idea here is to be able to visualize _how_ insects get to the "target point" when rendering the game after `selectOld` has been executed.

Here's an screenshot from a running example (locally) where selected spider has two moves available

<img width="274" alt="image" src="https://user-images.githubusercontent.com/1032755/46581823-edba6900-ca3e-11e8-97b8-ad9ce430f726.png">

The way this is implemented is by changing `availablePoints` (array of `point`) to `availableMoves` as an array of arrays of points. In each inner array of length _n_ the _n-1_ first elements are an ordered list of a "path" that leads to the "target", located at the end of the array. I'm saying ordered, as we might want to do some fancy animated rendering at a later point (currently only rendered as static yellow background)

Introducing this can be made in steps, as already implemented insects can have "move arrays" of one element (the target).

**Comment by Korla** [comment]
This is a great idea. For the intermediate step, how do you envision the ant rendering?

**Comment by pardahlman** [comment]
So for the ant, it would contain multiple moves (aka `point[][]`), but each move (`point[]`) would only contain on point, namely the _target point_. The result would be an rendering identical to how it is today.

I think an more interesting question is: how will the moves be rendered for the ant in the future, where multiple points can be both target for a move as well as part of the path in another move. It could perhaps be a nice experience if the "path" is rendered only when you hover a target? Not sure, just thinking aloud here 😛
